[General]
arkaPlan=#000000
tusRengi=#121212
basiliRenk=#3a3a3a
cerceveRengi=#5a5a5a
cerceveKalinligi=1
koseYaricapi=6
yaziRengi=#ffffff
satirAraligi=1.0
tusAraligi=0.5
tusYuksekligi=34
sayiSatiri=false
